---
dist: focal
matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - ANSIBLE='ansible>=2.8'
        - MOLECULE_SCENARIO="default"
      services: docker
      language: python
      python: "3.8"
      addons:
        snaps:
          - name: lxd
            channel: stable
#    - os: linux
#      env:
#        - ANSIBLE='ansible>=2.8'
#        - MOLECULE_SCENARIO="default"
#        - MOLECULE_DISTRIBUTION="archlinux"
#        - MOLECULE_IMAGE="manjarolinux/base:latest"
#      services: docker
#      language: python
#      python: "3.8"

install:
  - sudo usermod -aG lxd $USER
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - newgrp lxd
  - pip3 install -U pip
  - pip3 install "$ANSIBLE" testinfra molecule molecule-lxd docker flake8 ansible-lint yamllint
script:
  - python --version
  - molecule --version
  - ansible --version
  - molecule test -s $MOLECULE_SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
