---
- name: Install vim plugin manager
  shell:
    cmd: |
      set -o pipefail
      curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    creates: "~/.local/share/nvim/site/autoload/plug.vim"
    executable: /bin/bash
  environment:
    HOME: "{{ nvim_user_home }}"
  become: yes
  become_user: "{{ nvim_user }}"

- name: Clone nvim config from git repo
  git:
    repo: "{{ nvim_git_repo }}"
    version: "{{ nvim_git_branch }}"
    dest: "{{ nvim_git_dest }}"
  register: nvim_git_result
  changed_when: "nvim_git_result.after|default('after') != nvim_git_result.before|default('before')"
  become: yes
  become_user: "{{ nvim_user }}"

- name: Ensure XDG_RUNTIME_DIR exsists
  file:
    path: /run/user/{{ nvim_user_uid }}
    state: directory
    owner: "{{ nvim_user_uid }}"
    group: "{{ nvim_user_gid }}"
    mode: 0700

- name: Install neovim plugins
  shell:
    cmd: |
      set -o pipefail
      pyenv shell {{ nvim_python_ver }}
      nvim --headless +'PlugInstall --sync' +'PlugUpdate' +qa
    executable: /bin/bash
  environment:
    PATH: "{{ pyenv_root }}/bin:{{ fnm_default_nodejs_path }}:/usr/loca/bin:{{ ansible_env.PATH }}"
  register: nvim_plugin_install
  changed_when: nvim_plugin_install.stdout_lines|length > 5
  become: yes
  become_user: "{{ nvim_user }}"

# TODO: Install LSP Servers via LspInstall
