---
# tasks file for ansible-pyenv
- name: Set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

# tasks file for ansible-nvim
- name: Define role facts
  include_tasks: "define-role-facts.yml"

- name: Install nvim config and prerequistes
  include_tasks: "install-nvim-config.yml"
