---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: lxd
lint: |
    yamllint .
    ansible-lint .
    flake8
platforms:
  - name: "ansible-nvim-${MOLECULE_DISTRIBUTION:-ubuntu-focal}"
    alias: "${MOLECULE_IMAGE:-ubuntu/focal}"
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    destroy: ../resources/playbooks/destroy.yml
  options:
    vvv: True
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
